### ISSUE TITLE
yleareena 1.7.1: wrong type in useSocks setting 

### ISSUE THREAD

**Issue by jonekoo** [szymex/xbmc-finnish-tv#66]
causes only the internationally available shows to work. Fix is easy and was given in http://forum.xbmc.org/showthread.php?tid=144457&pid=1567407#pid1567407
a while ago. 

On line 75 of yleareena.py (1.7.1)change
useSocks = settings.getSetting('socks-use')
to 
useSocks = int(settings.getSetting('socks-use'))

Tested on Raspbmc. 

Thanks for the nice plugins anyway!

**Comment by szymex** [comment]
This should be fixed a while ago, please reopen ticket if you still have problems.
