### ISSUE TITLE
Yle Areena doesn't work

### ISSUE THREAD

**Issue by jussike** [szymex/xbmc-finnish-tv#70]
I'm running XBMC (Kodi) on my Raspberry Pi with latest Raspbmc build.

I tried to watch Yle Areena with your add-on but I just get Script Failed -error.
Which logs you need to debug it?

**Comment by tigert** [comment]
Install python-crypto from command line as root if you already didn't:
   pi@raspbmc:~$ sudo su
   root@raspbmc:/home/pi# apt-get install python-crypto

**Comment by tigert** [comment]
The log is in /home/pi/.kodi/temp/kodi.log. When you enable debugging, you can see the log filename on your screen.

**Comment by tigert** [comment]
Oh, for Kodi this might be related to your issue as well, if you already have the crypto installed:

https://github.com/szymex/xbmc-finnish-tv/pull/68

**Comment by szymex** [comment]
Yle Areena should work no in Kodi.

**Comment by jussike** [comment]
Thanks for fixing this issue.
