### ISSUE TITLE
HDS streams support in latest yle-dl

### ISSUE THREAD

**Issue by tigert** [szymex/xbmc-finnish-tv#71]
Looks like there is support for HDS streams in yle-dl via an additional script (that adds php executable as a dependency, though).

I tried just replacing the old yle-dl with the new in lib/ but looks like the functions and parameters have changed somewhat, so it was not trivial, and I have to dig deeper. Also, the download seems to pull in the video in chunks which are then compiled to the video file in the end, thus it might be even more complicated in terms of streaming. Areena in HD would be sweet in xbmc though.

The downside here is that I cannot really code, I just get by with bad hacks and fools luck. Maybe someone who can actually code should be able to do it a lot faster than me?

**Comment by szymex** [comment]
Is it possible to play HDS streams in Kodi?

**Comment by szymex** [comment]
Maybe it is possible with some localproxy. I created branch with HDS live channels. At least in my Raspberry PI + OpenElec it works.

**Comment by szymex** [comment]
Now it looks like HD streaming works without hds (after update with yledl 2.7.0)
