### ISSUE TITLE
YLE Areena stopped working

### ISSUE THREAD

**Issue by KajWiik** [szymex/xbmc-finnish-tv#82]
Apparently after changes in YLE areena webpage, the plugin stopped working giving 'Script failed!' error when trying to access the videos.

**Comment by tigert** [comment]
http://forum.kodi.tv/showthread.php?tid=144457

TL;DR: The old areena is still accessible as areena-v3.yle.fi, so you can change yleareena.py and lib/yle-dl.py and replace areena with areena-v3. Here's one way to do it quickly:

```perl -pi -e "s/areena.yle.fi/areena-v3.yle.fi/g" yleareena.py lib/yle-dl.py```

**Comment by KajWiik** [comment]
Worked, many thanks!

**Comment by szymex** [comment]
Can you make a pull request with your changes?
